// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBWhoF74vydRSF1dYW3SQnc7X4aIEjROkk",
      authDomain: "pdf-read-decbc.firebaseapp.com",
      databaseURL: "https://pdf-read-decbc-default-rtdb.firebaseio.com",
      projectId: "pdf-read-decbc",
      storageBucket: "pdf-read-decbc.appspot.com",
      messagingSenderId: "874393971124",
      appId: "1:874393971124:web:27ab6f3a52a3e08c772ae1",
      measurementId: "G-NJZ0K8W31Y"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-1XSYqb5UH-AdOmcoHq-kG8Ec4ag9aA',
    appId: '1:874393971124:android:81537a9a92ff3b38772ae1',
    messagingSenderId: '874393971124',
    projectId: 'pdf-read-decbc',
    storageBucket: 'pdf-read-decbc.appspot.com',
  );
}
